apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy: {}
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
#        volumeMounts:
#          - mountPath: /var/lib/postgresql/data
#            name: postgresql-data
#      volumes:
#        - name: postgresql-data
#          hostPath:
#            path: /host-data/data

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  type: NodePort
